changesetBaseRefs:
  - head

changesetIgnorePatterns:
  - "**/dist/*"
  - "**/packages/*"
  - "**/.*"
  - .**/*

compressionLevel: mixed

enableGlobalCache: true

enableInlineBuilds: true

logFilters:
  - code: YN0060
    level: discard
  - level: discard
    pattern: "secp256k1@npm:4.0.3 STDERR*"

nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  "@storybook/mdx1-csf@*":
    peerDependencies:
      "@babel/core": "*"
      react: "*"
  eslint-config-react-app@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
